#!/usr/bin/env bash
set -e

IVY_CLASSPATH=.ivy_classpath
IVY_SELF="ivy"

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

check_global_switch() {
  if [ "$1" != "$2" ]; then
    local argname=$1
    shift 2
    local remaining_command=${@#"$argname"}
    echo "Global switch ($argname) passed to sub-command. Perhaps you meant: $IVY_SELF $argname $remaining_command"
    exit 1
  fi
}

for a in "$@"; do
  case "$a" in
    --test)
      check_global_switch $a $1 $@
      export _IVY_CLI_TEST=yes
      shift
      ;;
    *)
      # let sub do the rest
      ;;
  esac
done

[ ! -z "$_IVY_CLI_TEST" ] && echo $@

libexec_path="$(abs_dirname "$0")"
export _IVY_ROOT="$(abs_dirname "$libexec_path")"
export PATH="${libexec_path}:$PATH"

command="$1"
case "$command" in
"" )
  exec ivy-exec -cachepath $IVY_CLASSPATH
  ;;
"-h" | "--help" )
  exec ivy-help
  ;;
* )
  command_path="$(command -v "ivy-$command" || true)"
  if [ ! -x "$command_path" ]; then
    echo "ivy: no such command \`$command'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
