#!/usr/bin/env bash
# Usage: ivy remove-package <package name(s)>
# Summary: Removes a package installed via `ivy install package` and any related shims, if they can be removed

set -e

IVY_PACKAGES_ROOT=$_IVY_ROOT/packages
IVY_SHIMS=$_IVY_ROOT/shims

# Provide ivy completions
if [ "$1" = "--complete" ]; then
    ls $IVY_PACKAGES_ROOT
    exit
fi


function _remove_package() {
    package=$1

    if [ ! -d $IVY_PACKAGES_ROOT/$package ]; then
        echo "Don't recognize $package as an installed package. Aborting"
        exit 1
    fi

    for bin in $IVY_PACKAGES_ROOT/$package/bin/*; do
        binname=$(basename $bin)
        rm -f $IVY_SHIMS/.index/$binname/$package
        set +e
        versions=( $(ls $IVY_SHIMS/.index/$binname 2> /dev/null) )
        set -e
        if [ ${#versions[@]} -eq 0 ]; then
            rm -rf $IVY_SHIMS/.index/$binname
            rm -f $IVY_SHIMS/$binname
        fi
    done

    rm -r $IVY_PACKAGES_ROOT/$package

    echo "Successfully remove package $package"
}

for package in "$@"; do
    _remove_package $package
done
