#!/usr/bin/env bash
# Usage: ivy build [<file name>]
# Summary: Compiles your src directory using ivy's resolved classpath

set -e

ivy exec -cachepath .ivy_classpath -error

CLASSPATH=`cat .ivy_classpath`

if [ -n "$CLASSPATH" ]; then
  COMPILE_CLASSPATH="-cp $CLASSPATH"
fi

if [ -z "$1" ]; then
  find ./src/ -type f -name "*.java" -print0 | xargs -n 1 -0 javac -d ./.classes -sourcepath ./src $COMPILE_CLASSPATH
else
  javac -d ./.classes -sourcepath ./src $COMPILE_CLASSPATH $@
fi
