#!/usr/bin/env bash
# Usage: ivy exec <ivy-options>
# Summary: Make a call directly to the ivy.jar
# Help: Call "ivy exec -?" to get a list of options you can pass in
# This is the same as the list found on the Apachy Ivy page covering
# stand alone execution http://ant.apache.org/ivy/history/latest-milestone/standalone.html

if [ -z "$IVY_HOME" ]; then
    IVY_HOME="$HOME/.ivy2"
fi

IVY_JAR=`ls $IVY_HOME/bin/ivy*.jar 2> /dev/null`

if [ -z "$IVY_JAR" ]; then
    #/bin didn't work, try /lib (Ant based $IVY_HOMEs)
    IVY_JAR=`ls $IVY_HOME/lib/ivy*.jar 2> /dev/null`
fi

if [ -z "$IVY_JAR" ]; then
    echo "Unable to find ivy.jar. Are you sure IVY_HOME is set correctly?"
    exit 1
fi

java -jar $IVY_JAR "$@"
