#!/usr/bin/env bash
# Usage: ivy exec <ivy-options>
# Summary: Make a call directly to the ivy.jar
# Help: ivy exec -? to get a list of options you can pass in

if [ -z "$IVY_HOME" ]; then
    IVY_HOME="$HOME/.ivy2"
fi

java -jar `ls $IVY_HOME/bin/ivy*.jar` $@
