#!/usr/bin/env bash
# Usage: ivy install <organization> <module> <revision> [<ivy-options>]
# Summary: Download a dependency to your local repository

set -e

if [ -z "$IVY_HOME" ]; then
    IVY_HOME="$HOME/.ivy2"
fi

if [ $# -lt 3 ]; then
    exec ivy help install
fi

java -jar `ls $IVY_HOME/bin/ivy*.jar` -dependency $@
