#!/usr/bin/env bash
# Usage: ivy install <organization> <module> <revision> [<ivy-options>]
# Summary: Download a dependency to your local repository

set -e

if [ $# -lt 3 ]; then
    exec ivy help install
fi

exec ivy exec -dependency $@
