#!/usr/bin/env bash
# Usage: ivy run main.Class [<arguments>,...]
# Summary: Run the current project using the ivy generated classpath to compile and execute the current project

set -e

ivy build

CLASSPATH=`cat .ivy_classpath`

if [ -n "$CLASSPATH" ]; then
    CLASSPATH="$CLASSPATH:"
fi

java -cp "$CLASSPATH./.classes" "$@"
