#!/usr/bin/env bash
# Usage: ivy rehash
# Summary: Create any missing bin commands from downloaded jars with executables (bin)

set -e

if [ "$1" = "--complete" ]; then
    exit
fi

IVY_PACKAGES_ROOT=$_IVY_ROOT/packages

IVY_SHIMS=$_IVY_ROOT/shims

[ -d $IVY_PACKAGES_ROOT ] || mkdir $IVY_PACKAGES_ROOT

function generate_shim() {
    local libdir=$1
    local binname=$2

    binname=$(basename $binname)
    local libname=$(basename $libdir) # just the name of the lib (implicitly includes versioning info)
    [ -n "$_IVY_CLI_TEST" ] && echo $binname, $libname && return 0

    if [ ! -f $IVY_SHIMS/$binname ]; then
        ln -s $_IVY_ROOT/libexec/shim $IVY_SHIMS/$binname
        mkdir -p $IVY_SHIMS/.index/$binname
    fi
    touch $IVY_SHIMS/.index/$binname/$libname
}

for lib in $IVY_PACKAGES_ROOT/*/; do
    lib=${lib%*/} # remove trailing slash so the line below looks a bit cleaner
    for bin in $lib/bin/*; do
        generate_shim $lib $bin
    done
done
